import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// ULTRA-COMPLETE Albanian translations - EVERY text in the website
const albanianTranslations: Record<string, string> = {
  // ============= NAVIGATION =============
  'Fleet': 'Flota',
  'Technology': 'Teknologjia',
  'About': 'Rreth Nesh',
  'Request Pricing': 'Kërko Çmimin',
  'Contact': 'Kontakt',
  'Home': 'Ballina',
  
  // ============= HERO SECTION =============
  'The Future of Sustainable Mobility': 'E Ardhmja e Mobilitetit të Qëndrueshëm',
  'Experience cutting-edge electric vehicles that combine performance, efficiency, and environmental responsibility.': 'Përjetoni automjete elektrike të avancuara që kombinojnë performancën, efikasitetin dhe përgjegjësinë mjedisore.',
  'Explore Cars': 'Eksploro Makinat',
  'Watch Video': 'Shiko Videon',
  'Discover More': 'Zbulo Më Shumë',
  
  // ============= STATS SECTION =============
  'Vehicles Sold': 'Automjete të Shitura',
  'CO₂ Saved': 'CO₂ e Kursyer',
  'Countries': 'Vende',
  'Charging Stations': 'Stacione Karikimi',
  'Happy Customers': 'Klientë të Lumtur',
  'Awards Won': 'Çmime të Fituara',
  'tons': 'tonë',
  
  // ============= FLEET SECTION =============
  'REQUEST PRICING': 'KËRKO ÇMIMIN',
  'Our Fleet': 'Flota Jonë',
  'Discover our range of electric vehicles designed for every need': 'Zbuloni gamën tonë të automjeteve elektrike të dizajnuara për çdo nevojë',
  'View Details': 'Shiko Detajet',
  'Learn More': 'Mëso Më Shumë',
  'Explore Fleet': 'Eksploro Flotën',
  'All Models': 'Të Gjitha Modelet',
  'Available Now': 'I Disponueshëm Tani',
  'Coming Soon': 'Vjen Së Shpejti',
  'Pre-Order': 'Porosit Paraprakisht',
  'Starting from': 'Duke filluar nga',
  'Book Test Drive': 'Rezervo Test Drive',
  
  // ============= VEHICLE CATEGORIES =============
  'All': 'Të Gjitha',
  'Sedan': 'Sedan',
  'SUV': 'SUV',
  'Compact': 'Kompakte',
  'Luxury': 'Luks',
  'Sport': 'Sportive',
  'Family': 'Familjare',
  'Commercial': 'Komerciale',
  
  // ============= TECHNOLOGY SECTION =============
  'Our Technology': 'Teknologjia Jonë',
  'Cutting-edge innovation for sustainable transportation': 'Inovacioni më i fundit për transport të qëndrueshëm',
  'Advanced Battery Technology': 'Teknologji e Avancuar e Baterisë',
  'Autonomous Driving': 'Drejtim Autonom',
  'Smart Connectivity': 'Lidhje Inteligjente',
  'Sustainable Manufacturing': 'Prodhim i Qëndrueshëm',
  'Regenerative Braking': 'Frenimi Rigjenerues',
  'Over-the-Air Updates': 'Përditësime Over-the-Air',
  'AI-Powered Systems': 'Sisteme të Fuqizuara me AI',
  'Vehicle-to-Grid': 'Vehicle-to-Grid',
  
  // ============= FEATURES DESCRIPTIONS =============
  'Next-generation lithium-ion batteries with extended range and faster charging capabilities': 'Bateri litium-jon të gjeneratës së re me rreze të zgjatur dhe aftësi karikimi më të shpejtë',
  'Level 4 autonomous driving capabilities for safer and more comfortable journeys': 'Aftësi të drejtimit autonom të nivelit 4 për udhëtime më të sigurta dhe më të rehatshme',
  'Seamless integration with your digital life through our advanced infotainment system': 'Integrim i përsosur me jetën tuaj dixhitale përmes sistemit tonë të avancuar infotainment',
  'Zero-emission production facilities powered entirely by renewable energy': 'Objekte prodhimi me zero emetime të fuqizuara plotësisht nga energjia e rinovueshme',
  
  // ============= SUSTAINABILITY SECTION =============
  'Sustainability': 'Qëndrueshmëria',
  'Building a greener future through electric mobility': 'Ndërtimi i një të ardhmeje më të gjelbër përmes mobilitetit elektrik',
  'Carbon Neutral': 'Neutral ndaj Karbonit',
  'Renewable Energy': 'Energji e Rinovueshme',
  'Recycling Program': 'Programi i Riciklimit',
  'Eco-Friendly Materials': 'Materiale Miqësore ndaj Mjedisit',
  'Our Commitment': 'Angazhimi Ynë',
  'Environmental Impact': 'Ndikimi Mjedisor',
  'Green Initiative': 'Nisma e Gjelbër',
  
  // ============= ABOUT US PAGE =============
  'About Us': 'Rreth Nesh',
  'Our Mission': 'Misioni Ynë',
  'Our Vision': 'Vizioni Ynë',
  'Our Values': 'Vlerat Tona',
  'Leadership Team': 'Ekipi Drejtues',
  'History': 'Historia',
  'Innovation': 'Inovacioni',
  'Excellence': 'Përsosmëria',
  'Integrity': 'Integriteti',
  'Sustainability First': 'Qëndrueshmëria Fillimisht',
  'Customer Focus': 'Fokusi te Klienti',
  'Meet Our Team': 'Takoni Ekipin Tonë',
  'Years of Experience': 'Vite Eksperiencë',
  'Global Presence': 'Prezencë Globale',
  'Join Our Journey': 'Bashkohuni në Udhëtimin Tonë',
  
  // ============= CONTACT PAGE =============
  'Contact Us': 'Na Kontaktoni',
  'Get in Touch': 'Lidhuni me Ne',
  'Send us a Message': 'Na Dërgoni një Mesazh',
  'Office Location': 'Vendndodhja e Zyrës',
  'Business Hours': 'Orari i Punës',
  'Follow Us': 'Na Ndiqni',
  'Call Us': 'Na Telefononi',
  'Email Us': 'Na Dërgoni Email',
  'Visit Our Showroom': 'Vizitoni Showroom-in Tonë',
  'Schedule a Meeting': 'Planifikoni një Takim',
  'Find a Dealer': 'Gjeni një Shitës',
  'Customer Support': 'Mbështetja e Klientit',
  'Monday - Friday': 'E Hënë - E Premte',
  'Saturday': 'E Shtunë',
  'Sunday': 'E Diel',
  'Closed': 'Mbyllur',
  
  // ============= CAR DETAIL PAGE =============
  'Available Editions': 'Edicionet e Disponueshme',
  'Overview': 'Përmbledhje',
  'Specifications': 'Specifikimet',
  'Features': 'Karakteristikat',
  'Gallery': 'Galeria',
  'Reviews': 'Vlerësimet',
  'Range': 'Distanca',
  'Top Speed': 'Shpejtësia Maksimale',
  'Acceleration': 'Përshpejtimi',
  'Battery Capacity': 'Kapaciteti i Baterisë',
  'Charging Time': 'Koha e Karikimit',
  'Seating Capacity': 'Kapaciteti i Ulësjeve',
  'Cargo Space': 'Hapësira e Bagazhit',
  'Warranty': 'Garancia',
  'Price': 'Çmimi',
  'Available': 'I Disponueshëm',
  'Out of Stock': 'Jashtë Stokut',
  'In Stock': 'Në Stok',
  'Limited Edition': 'Edicion i Kufizuar',
  'Reserve Now': 'Rezervo Tani',
  'Configure': 'Konfiguro',
  'Download Brochure': 'Shkarko Broshurën',
  'Share': 'Shpërndaj',
  'Compare': 'Krahaso',
  '0-100 km/h': '0-100 km/h',
  'km': 'km',
  'km/h': 'km/h',
  'kWh': 'kWh',
  'minutes': 'minuta',
  'hours': 'orë',
  'seats': 'ulëse',
  'liters': 'litra',
  'years': 'vite',
  
  // ============= REQUEST PRICING PAGE =============
  'Request a Quote': 'Kërko një Ofertë',
  'Get personalized pricing': 'Merrni çmime të personalizuara',
  'Fill out the form below and our team will contact you shortly': 'Plotësoni formularin më poshtë dhe ekipi ynë do t\'ju kontaktojë së shpejti',
  'Personal Information': 'Informacioni Personal',
  'Vehicle Preferences': 'Preferencat e Automjetit',
  'Additional Information': 'Informacion Shtesë',
  'Full Name': 'Emri i Plotë',
  'First Name': 'Emri',
  'Last Name': 'Mbiemri',
  'Email': 'Email',
  'Email Address': 'Adresa Email',
  'Phone Number': 'Numri i Telefonit',
  'Company Name': 'Emri i Kompanisë',
  'Country': 'Vendi',
  'City': 'Qyteti',
  'Preferred Model': 'Modeli i Preferuar',
  'Select Model': 'Zgjidhni Modelin',
  'Budget Range': 'Gama e Buxhetit',
  'Select Budget': 'Zgjidhni Buxhetin',
  'Message': 'Mesazhi',
  'How did you hear about us?': 'Si dëgjuat për ne?',
  'Send Request': 'Dërgo Kërkesën',
  'Submit': 'Dërgo',
  'Cancel': 'Anulo',
  'Required field': 'Fushë e detyrueshme',
  'Optional': 'Opsionale',
  'I agree to the terms and conditions': 'Pajtohem me kushtet dhe afatet',
  'Subscribe to newsletter': 'Abonohu në buletinin informativ',
  'Thank you for your request!': 'Faleminderit për kërkesën tuaj!',
  'We will contact you soon.': 'Do t\'ju kontaktojmë së shpejti.',
  
  // ============= ADMIN PANEL =============
  'Admin Login': 'Hyrja e Administratorit',
  'Admin Dashboard': 'Paneli i Administratorit',
  'Dashboard': 'Paneli',
  'Password': 'Fjalëkalimi',
  'Sign In': 'Hyr',
  'Sign Out': 'Dil',
  'Logout': 'Dil',
  'Welcome back': 'Mirësevini',
  'Manage Fleet': 'Menaxho Flotën',
  'Manage Orders': 'Menaxho Porositë',
  'Manage Users': 'Menaxho Përdoruesit',
  'Analytics': 'Analitika',
  'Reports': 'Raportet',
  'Settings': 'Cilësimet',
  'Profile': 'Profili',
  'Add Vehicle': 'Shto Automjet',
  'Edit Vehicle': 'Modifiko Automjetin',
  'Delete Vehicle': 'Fshi Automjetin',
  'Vehicle List': 'Lista e Automjeteve',
  'Orders': 'Porositë',
  'Customers': 'Klientët',
  'Revenue': 'Të Ardhurat',
  'Total Sales': 'Shitjet Totale',
  'New Orders': 'Porosi të Reja',
  'Pending': 'Në Pritje',
  'Completed': 'Të Përfunduara',
  'Cancelled': 'Të Anuluara',
  'View All': 'Shiko të Gjitha',
  'Export': 'Eksporto',
  'Import': 'Importo',
  'Search': 'Kërko',
  'Filter': 'Filtro',
  'Sort': 'Rendit',
  'Date': 'Data',
  'Status': 'Statusi',
  'Action': 'Veprimi',
  
  // ============= FOOTER =============
  'Company': 'Kompania',
  'Products': 'Produktet',
  'Support': 'Mbështetje',
  'Socials': 'Rrjetet Sociale',
  'All rights reserved': 'Të gjitha të drejtat të rezervuara',
  'Privacy Policy': 'Politika e Privatësisë',
  'Terms of Service': 'Kushtet e Shërbimit',
  'Cookie Policy': 'Politika e Cookie',
  'Careers': 'Karriera',
  'Press': 'Shtypi',
  'Investors': 'Investitorët',
  'Partners': 'Partnerët',
  'Affiliates': 'Filialët',
  'Help Center': 'Qendra e Ndihmës',
  'Documentation': 'Dokumentacioni',
  'FAQ': 'Pyetje të Shpeshta',
  'Community': 'Komuniteti',
  'Blog': 'Blog',
  'Newsletter': 'Buletini',
  'Subscribe': 'Abonohu',
  'Unsubscribe': 'Çabonohu',
  
  // ============= COMMON UI ELEMENTS =============
  'Loading...': 'Duke ngarkuar...',
  'Loading': 'Duke ngarkuar',
  'Please wait': 'Ju lutemi prisni',
  'Error': 'Gabim',
  'Success': 'Sukses',
  'Warning': 'Paralajmërim',
  'Info': 'Info',
  'Close': 'Mbyll',
  'Open': 'Hap',
  'Save': 'Ruaj',
  'Save Changes': 'Ruaj Ndryshimet',
  'Delete': 'Fshi',
  'Edit': 'Modifiko',
  'Update': 'Përditëso',
  'Add': 'Shto',
  'Remove': 'Hiq',
  'Back': 'Prapa',
  'Next': 'Tjetër',
  'Previous': 'I Mëparshëm',
  'Finish': 'Përfundo',
  'Continue': 'Vazhdo',
  'Skip': 'Kalo',
  'Yes': 'Po',
  'No': 'Jo',
  'OK': 'OK',
  'Confirm': 'Konfirmo',
  'Are you sure?': 'Jeni të sigurt?',
  'Select': 'Zgjedh',
  'Select All': 'Zgjedh të Gjitha',
  'Deselect All': 'Ç\'zgjedh të Gjitha',
  'Choose': 'Zgjedh',
  'Browse': 'Shfleto',
  'Upload': 'Ngarko',
  'Download': 'Shkarko',
  'Refresh': 'Rifresko',
  'Reset': 'Rivendos',
  'Clear': 'Pastro',
  'Apply': 'Apliko',
  'Show More': 'Shfaq Më Shumë',
  'Show Less': 'Shfaq Më Pak',
  'View More': 'Shiko Më Shumë',
  'View Less': 'Shiko Më Pak',
  'Read More': 'Lexo Më Shumë',
  'Read Less': 'Lexo Më Pak',
  'See All': 'Shiko të Gjitha',
  'Hide': 'Fsheh',
  'Show': 'Shfaq',
  'Expand': 'Zgjero',
  'Collapse': 'Mbyll',
  'Copy': 'Kopjo',
  'Paste': 'Ngjit',
  'Cut': 'Prit',
  'Print': 'Printo',
  
  // ============= FORMS & VALIDATION =============
  'Required': 'E detyrueshme',
  'Invalid email': 'Email i pavlefshëm',
  'Invalid phone number': 'Numër telefoni i pavlefshëm',
  'Password too short': 'Fjalëkalimi shumë i shkurtër',
  'Passwords do not match': 'Fjalëkalimet nuk përputhen',
  'Please enter a valid email': 'Ju lutemi vendosni një email të vlefshëm',
  'Please enter your name': 'Ju lutemi vendosni emrin tuaj',
  'Please enter your message': 'Ju lutemi vendosni mesazhin tuaj',
  'Please select an option': 'Ju lutemi zgjidhni një opsion',
  'Please agree to the terms': 'Ju lutemi pranoni kushtet',
  'Form submitted successfully': 'Formulari u dërgua me sukses',
  'Something went wrong': 'Diçka shkoi keq',
  'Please try again': 'Ju lutemi provoni përsëri',
  
  // ============= CAROUSEL & ANIMATIONS =============
  'Slide': 'Sllajd',
  'Play': 'Luaj',
  'Pause': 'Pauzo',
  'Autoplay': 'Luaj automatikisht',
  'Full Screen': 'Ekran i Plotë',
  'Exit Full Screen': 'Dil nga Ekrani i Plotë',
  'Zoom In': 'Zmadho',
  'Zoom Out': 'Zvogëlo',
  'Rotate': 'Rrotullo',
  
  // ============= NOTIFICATIONS =============
  'New notification': 'Njoftim i ri',
  'Mark as read': 'Shëno si të lexuar',
  'Mark all as read': 'Shëno të gjitha si të lexuara',
  'Clear notifications': 'Pastro njoftimet',
  'No notifications': 'Nuk ka njoftime',
  'Settings updated': 'Cilësimet u përditësuan',
  'Profile updated': 'Profili u përditësua',
  'Password changed': 'Fjalëkalimi u ndryshua',
  
  // ============= SEARCH & FILTERS =============
  'Search results': 'Rezultatet e kërkimit',
  'No results found': 'Nuk u gjetën rezultate',
  'Showing results for': 'Duke shfaqur rezultatet për',
  'Filter by': 'Filtro sipas',
  'Sort by': 'Rendit sipas',
  'Price: Low to High': 'Çmimi: Nga i ulëti te i larti',
  'Price: High to Low': 'Çmimi: Nga i larti te i ulëti',
  'Newest First': 'Më të rejat fillimisht',
  'Oldest First': 'Më të vjetrat fillimisht',
  'Most Popular': 'Më të populluarat',
  'Best Rated': 'Më të vlerësuarat',
  'Alphabetical': 'Alfabetik',
  'Reset Filters': 'Rivendos Filtrat',
  'Apply Filters': 'Apliko Filtrat',
  
  // ============= DATES & TIME =============
  'Today': 'Sot',
  'Yesterday': 'Dje',
  'Tomorrow': 'Nesër',
  'This Week': 'Këtë Javë',
  'Last Week': 'Javën e Kaluar',
  'This Month': 'Këtë Muaj',
  'Last Month': 'Muajin e Kaluar',
  'This Year': 'Këtë Vit',
  'Last Year': 'Vitin e Kaluar',
  'January': 'Janar',
  'February': 'Shkurt',
  'March': 'Mars',
  'April': 'Prill',
  'May': 'Maj',
  'June': 'Qershor',
  'July': 'Korrik',
  'August': 'Gusht',
  'September': 'Shtator',
  'October': 'Tetor',
  'November': 'Nëntor',
  'December': 'Dhjetor',
  
  // ============= MISCELLANEOUS =============
  'Coming Soon ': 'Vjen Së Shpejti',
  'Under Construction': 'Në Ndërtim',
  'Beta': 'Beta',
  'New': 'E Re',
  'Hot': 'E Nxehtë',
  'Sale': 'Zbritje',
  'Limited Offer': 'Ofertë e Kufizuar',
  'Free Shipping': 'Transport Falas',
  'Bestseller': 'Më i shituri',
  'Featured': 'I Zgjedhur',
  'Recommended': 'I Rekomanduar',
  'Popular': 'Popullor',
  'Trending': 'Në trend',
  'Exclusive': 'Ekskluzive',
  'Premium': 'Premium',
  'Standard': 'Standard',
  'Basic': 'Bazike',
  'Advanced': 'E Avancuar',
  'Professional': 'Profesionale',
  'Enterprise': 'Enterprise',


    // ============= MISSING TRANSLATIONS =============
  // Fleet page
  'Zero emissions': 'Zero emetime',
  'models': 'modele',
  'Loading vehicles...': 'Duke ngarkuar automjetet...',
  'No vehicles available in this category.': 'Nuk ka automjete të disponueshme në këtë kategori.',
  'No vehicles available in this category': 'Nuk ka automjete të disponueshme në këtë kategori',
  'No vehicles available at this time.': 'Nuk ka automjete të disponueshme në këtë moment.',
  
  // Vehicle descriptions
  'Premium electric sedan': 'Sedan elektrik premium',
  'Compact SUV': 'SUV kompakt',
  '7-seater SUV': 'SUV 7-vendësh',
  'City car': 'Makinë qyteti',
  'Executive sedan': 'Sedan ekzekutiv',
  'range': 'distancë',
  'From': 'Nga',
  'Electric Vehicle': 'Automjet Elektrik',
  'Contact for pricing': 'Kontaktoni për çmim',
  'Unnamed Car': 'Makinë pa emër',
  
  // Request Pricing additions
  'Get Your Personalized Quote': 'Merrni Ofertën Tuaj të Personalizuar',
  'Fill in your details and we\'ll send you a tailored pricing offer': 'Plotësoni të dhënat tuaja dhe do t\'ju dërgojmë një ofertë çmimi të personalizuar',
  'Select your country': 'Zgjidhni vendin tuaj',
  'Choose a vehicle': 'Zgjidhni një automjet',
  'Tell us about your specific requirements, preferred payment options, or any questions...': 'Na tregoni për kërkesat tuaja specifike, opsionet e preferuara të pagesës, ose çdo pyetje...',
  'Submitting...': 'Duke dërguar...',
  'Submit Request': 'Dërgo Kërkesën',
  'Wide Selection': 'Zgjedhje e Gjerë',
  'Choose from our extensive fleet of premium electric vehicles': 'Zgjidhni nga flota jonë e gjerë e automjeteve elektrike premium',
  'Best Prices': 'Çmimet Më të Mira',
  'Competitive pricing with flexible payment options': 'Çmime konkurruese me opsione fleksibël pagese',
  'Fast Response': 'Përgjigje e Shpejtë',
  'Get your personalized quote within 24 hours': 'Merrni ofertën tuaj të personalizuar brenda 24 orëve',
  'Request Submitted Successfully!': 'Kërkesa u Dërgua me Sukses!',
  'We\'ll contact you within 24 hours with your personalized pricing.': 'Do t\'ju kontaktojmë brenda 24 orëve me çmimet tuaja të personalizuara.',
  'Redirecting to homepage...': 'Po ridrejtohet te faqja kryesore...',
  
  // ============= TECHNOLOGY PAGES =============
  // Navigation
  '← Back to Home': '← Kthehu në Ballina',
  'Blade Battery': 'Bateria Blade',
  'e-Platform 3.0': 'e-Platforma 3.0',
  'Energy Management': 'Menaxhimi i Energjisë',
  
  // Blade Battery page
  'Revolutionary LFP Technology': 'Teknologji Revolucionare LFP',
  'Blade Battery Technology': 'Teknologjia e Baterisë Blade',
  'The safest battery technology ever developed. Zero thermal runaway risk, 1 million kilometer lifespan, and 96% recyclable materials.': 'Teknologjia më e sigurt e baterisë e zhvilluar ndonjëherë. Zero rrezik termik, 1 milion kilometra jetëgjatësi dhe 96% materiale të riciklueshme.',
  'Cobalt Required': 'Kobalt i Nevojshëm',
  'Charge Cycles': 'Cikle Karikimi',
  'CO₂ Emissions': 'Emetimet e CO₂',
  'How Blade Battery Works': 'Si Funksionon Bateria Blade',
  'Cell-to-Pack Design': 'Dizajn Cell-to-Pack',
  'Traditional battery packs use cylindrical cells with wasted space. Blade Battery\'s elongated cells are arranged directly into the pack, increasing space utilization by 50% while serving as structural components.': 'Paketat tradicionale të baterive përdorin qeliza cilindrike me hapësirë të humbur. Qelizat e zgjatura të Baterisë Blade vendosen direkt në paketë, duke rritur përdorimin e hapësirës me 50% ndërkohë që shërbejnë si komponentë strukturorë.',
  'LFP Chemistry': 'Kimia LFP',
  'Lithium Iron Phosphate (LFP) chemistry eliminates cobalt and nickel, using abundant iron and phosphate. This makes batteries cheaper, safer, and more environmentally friendly without toxic heavy metals.': 'Kimia e Fosfatit të Hekurit të Litiumit (LFP) eliminon kobaltin dhe nikelin, duke përdorur hekur dhe fosfat të bollshëm. Kjo i bën bateritë më të lira, më të sigurta dhe më miqësore ndaj mjedisit pa metale të rënda toksike.',
  'Thermal Stability': 'Stabiliteti Termik',
  'LFP chemistry is inherently stable, requiring temperatures above 500°C to decompose. Even when punctured, crushed, or overcharged, Blade Battery doesn\'t catch fire or explode.': 'Kimia LFP është e qëndrueshme në thelb, duke kërkuar temperatura mbi 500°C për t\'u dekompozuar. Edhe kur shpohet, shtyhet ose mbingarkohet, Bateria Blade nuk merr flakë ose shpërthen.',
  'Environmental Benefits': 'Përfitimet Mjedisore',
  'No child labor or conflict minerals from cobalt mining in the Democratic Republic of Congo': 'Pa punë fëmijësh ose minerale konflikti nga minierat e kobaltit në Republikën Demokratike të Kongos',
  'Kilometer Lifespan': 'Jetëgjatësia në Kilometra',
  'Lasts 3-4x longer than traditional batteries, reducing replacement waste and resource consumption': 'Zgjat 3-4 herë më shumë se bateritë tradicionale, duke reduktuar mbetjet e zëvendësimit dhe konsumin e burimeve',
  'Recyclable Materials': 'Materiale të Riciklueshme',
  'Iron, phosphate, and lithium can be recovered and reused in new batteries or other industries': 'Hekuri, fosfati dhe litiumi mund të rikuperohen dhe ripërdoren në bateri të reja ose industri të tjera',
  'Manufacturing Emissions': 'Emetimet e Prodhimit',
  'Simpler chemistry and abundant materials reduce production CO₂ compared to NMC batteries': 'Kimia më e thjeshtë dhe materialet e bollshme reduktojnë CO₂ e prodhimit krahasuar me bateritë NMC',
  'Technical Specifications': 'Specifikimet Teknike',
  'Energy Density': 'Dendësia e Energjisë',
  'Cycle Life': 'Jeta e Ciklit',
  '5,000+ cycles to 80% capacity': '5,000+ cikle deri në 80% kapacitet',
  'Operating Temperature': 'Temperatura e Operimit',
  'Charge Rate': 'Shkalla e Karikimit',
  '10-80% in 30 minutes': '10-80% në 30 minuta',
  'Thermal Runaway': 'Shpërthimi Termik',
  'No propagation even when penetrated': 'Pa përhapje edhe kur depërtohet',
  'Experience the Future of Battery Technology': 'Përjetoni të Ardhmen e Teknologjisë së Baterisë',
  'Every Blade Battery vehicle reduces lifetime emissions by 40 tons of CO₂': 'Çdo automjet me Bateri Blade redukton emetimet gjatë jetës me 40 tonë CO₂',
  'Explore Our Fleet': 'Eksploro Flotën Tonë',
  
  'Advanced Technology': 'Teknologji e Avancuar',
  'Click to explore our revolutionary innovations': 'Klikoni për të eksploruar inovacionet tona revolucionare',
  'Intelligent energy optimization with regenerative braking and V2G capability. Smart grid integration.': 'Optimizim inteligjent i energjisë me frenim rigjenerues dhe aftësi V2G. Integrim inteligjent në rrjet.',
  'Revolutionary LFP battery technology delivering unmatched safety, longevity, and performance. Over 1 million kilometers lifespan.': 'Teknologjia revolucionare e baterisë LFP që ofron siguri, jetëgjatësi dhe performancë të pakrahasueshme. Mbi 1 milion kilometra jetëgjatësi.',
  '8-in-1 integrated platform with revolutionary efficiency. Simplified architecture for maximum performance.': 'Platformë e integruar 8-në-1 me efikasitet revolucionar. Arkitekturë e thjeshtuar për performancë maksimale.',
  'Every Kilometer Matters': 'Çdo Kilometër ka Rëndësi',
  'Direct Emissions': 'Emetime të Drejtpërdrejta',
  'Recyclable': 'Të Riciklueshme',
  'Carbon vs ICE': 'Karboni vs ICE',
  // e-Platform page
  'Revolutionary Integration': 'Integrim Revolucionar',
  '8-in-1 integration that revolutionizes electric vehicle efficiency. 40% less volume, 23% less weight, and 10% higher efficiency than traditional EVs.': 'Integrim 8-në-1 që revolucionarizon efikasitetin e automjeteve elektrike. 40% më pak vëllim, 23% më pak peshë dhe 10% efikasitet më i lartë se automjetet tradicionale elektrike.',
  '8-in-1': '8-në-1',
  'Power Module': 'Moduli i Fuqisë',
  'System Efficiency': 'Efikasiteti i Sistemit',
  'Component Volume': 'Vëllimi i Komponentëve',
  'Revolutionary Integration ': 'Integrim Revolucionar',
  'Traditional EV': 'Automjet Elektrik Tradicional',
  'Separate Motor': 'Motor i Veçantë',
  'Standalone Controller': 'Kontrollues i Pavarur',
  'Individual Transmission': 'Transmision Individual',
  'Isolated Power Distribution': 'Shpërndarje e Izoluar e Fuqisë',
  'Multiple Cooling Systems': 'Sisteme të Shumta Ftohëse',
  'Complex Wiring': 'Instalime Komplekse',
  'Weight': 'Pesha',
  'Volume': 'Vëllimi',
  'Efficiency': 'Efikasiteti',
  '8-in-1 Power Module': 'Moduli i Fuqisë 8-në-1',
  'Integrated Cooling': 'Ftohje e Integruar',
  'Simplified Architecture': 'Arkitekturë e Thjeshtuar',
  '20% Less Raw Materials': '20% Më Pak Lëndë të Para',
  'Integration eliminates redundant housings, connectors, and cooling systems. This means 20% less aluminum, copper, and rare earth materials per vehicle.': 'Integrimi eliminon mbështjelljet, lidhëset dhe sistemet ftohëse të tepërta. Kjo do të thotë 20% më pak alumin, bakër dhe materiale të rralla për automjet.',
  '10% Higher Efficiency': '10% Efikasitet Më i Lartë',
  'Shorter power paths and optimized thermal management increase drivetrain efficiency from 82% to 89%, meaning 10% more range from the same battery.': 'Rrugët më të shkurtra të fuqisë dhe menaxhimi i optimizuar termik rrisin efikasitetin e transmisionit nga 82% në 89%, që do të thotë 10% më shumë distancë nga e njëjta bateri.',
  'Easier Recycling': 'Riciklim Më i Lehtë',
  'Modular design allows entire power unit replacement and refurbishment. Components are easier to separate and recycle at end of life.': 'Dizajni modular lejon zëvendësimin dhe rinovimin e të gjithë njësisë së fuqisë. Komponentët janë më të lehtë për t\'u ndarë dhe ricikluar në fund të jetës.',
  'Simplified Manufacturing': 'Prodhim i Thjeshtuar',
  '40% fewer parts mean less factory equipment, lower energy consumption, and reduced manufacturing emissions per vehicle.': '40% më pak pjesë do të thotë më pak pajisje fabrike, konsum më të ulët energjie dhe emetime të reduktuara prodhimi për automjet.',
  'Wide-Temperature Heat Pump': 'Pompë Nxehtësie me Temperaturë të Gjerë',
  'Energy Recovery System': 'Sistemi i Rikuperimit të Energjisë',
  'The integrated heat pump captures waste heat from the motor, inverter, and battery, using it for cabin heating. This revolutionary system works efficiently even at -30°C.': 'Pompa e integruar e nxehtësisë kap nxehtësinë e humbur nga motori, inverteri dhe bateria, duke e përdorur për ngrohjen e kabinës. Ky sistem revolucionar funksionon me efikasitet edhe në -30°C.',
  'Less Energy for Heating': 'Më Pak Energji për Ngrohje',
  'Winter Range Improvement': 'Përmirësimi i Distancës në Dimër',
  'Engineering Excellence for Sustainability': 'Përsosmëri Inxhinierike për Qëndrueshmëri',
  'Every e-Platform 3.0 vehicle saves 2 tons of CO₂ in manufacturing': 'Çdo automjet me e-Platform 3.0 kursen 2 tonë CO₂ në prodhim',
  'Discover Our Technology': 'Zbulo Teknologjinë Tonë',
  
  // Energy Management page
  'days': 'ditë',
  'Intelligent Optimization': 'Optimizim Inteligjent',
  'Energy Management System': 'Sistemi i Menaxhimit të Energjisë',
  'AI-powered system that maximizes efficiency and minimizes environmental impact. Smart regeneration, V2G capability, and adaptive driving modes.': 'Sistem i fuqizuar me AI që maksimizon efikasitetin dhe minimizon ndikimin mjedisor. Rigjenerim i zgjuar, aftësi V2G dhe modalitete adaptive të drejtimit.',
  'Energy Recovery': 'Rikuperimi i Energjisë',
  'Grid Support': 'Mbështetje për Rrjetin',
  'City Range': 'Distanca në Qytet',
  'Adaptive Driving Modes': 'Modalitete Adaptive të Drejtimit',
  'Eco': 'Eko',
  'Normal': 'Normal',
  'Sport ': 'Sport',
  'ECO Mode - Maximum Efficiency': 'Modaliteti EKO - Efikasitet Maksimal',
  'Optimizes every joule of energy for maximum range': 'Optimizon çdo xhaul energjie për distancë maksimale',
  'Range Extension': 'Zgjatja e Distancës',
  'Power Consumption': 'Konsumi i Energjisë',
  'Regeneration': 'Rigjenerimi',
  'Normal Mode - Balanced Performance': 'Modaliteti Normal - Performancë e Ekuilibruar',
  'Intelligent balance between efficiency and responsiveness': 'Ekuilibër inteligjent midis efikasitetit dhe reagimit',
  'Optimal': 'Optimal',
  'Daily Driving': 'Drejtimi i Përditshëm',
  'Smart': 'I Zgjuar',
  'Power Delivery': 'Dhënia e Fuqisë',
  'Sport Mode - Peak Performance': 'Modaliteti Sport - Performancë Maksimale',
  'Maximum power delivery for spirited driving': 'Dhënie maksimale e fuqisë për drejtim sportiv',
  'Power Available': 'Fuqi e Disponueshme',
  'Enhanced': 'E Përmirësuar',
  'Throttle Response': 'Reagimi i Pedalit',
  'Regenerative Braking System': 'Sistemi i Frenimit Rigjenerues',
  'Energy Recovery Technology': 'Teknologjia e Rikuperimit të Energjisë',
  'Our advanced regenerative braking system captures up to 90% of kinetic energy during deceleration, converting it back into electricity to charge the battery. This recovered energy would otherwise be lost as heat in traditional friction brakes.': 'Sistemi ynë i avancuar i frenimit rigjenerues kap deri në 90% të energjisë kinetike gjatë ngadalësimit, duke e kthyer në energji elektrike për të karikuar baterinë. Kjo energji e rikuperuar përndryshe do të humbiste si nxehtësi në frenat tradicionale me fërkim.',
  'Range increase in city driving': 'Rritje e distancës në drejtim në qytet',
  'Less brake pad wear': 'Më pak konsumim i frenave',
  'CO₂ saved per year': 'CO₂ e kursyer në vit',
  'Vehicle-to-Grid (V2G) Technology': 'Teknologjia Vehicle-to-Grid (V2G)',
  'Your Car as a Power Station': 'Makina Juaj si Stacion Energjie',
  'With V2G technology, your vehicle becomes a mobile energy storage unit. During peak renewable energy production, charge your car with clean energy. During peak demand, sell energy back to the grid or power your home during outages.': 'Me teknologjinë V2G, automjeti juaj bëhet një njësi mobile ruajtjeje e energjisë. Gjatë prodhimit maksimal të energjisë së rinovueshme, karikoni makinën tuaj me energji të pastër. Gjatë kërkesës maksimale, shisni energji përsëri në rrjet ose furnizoni shtëpinë tuaj gjatë ndërprerjeve.',
  'Annual earnings potential': 'Potenciali vjetor i fitimeve',
  'Home backup power': 'Energji rezervë për shtëpinë',
  'Renewable integration': 'Integrimi i rinovueshme',
  'Smart Energy for a Sustainable Future': 'Energji e Zgjuar për një të Ardhme të Qëndrueshme',
  'Our intelligent systems reduce grid strain and maximize renewable energy use': 'Sistemet tona inteligjente reduktojnë ngarkesën e rrjetit dhe maksimizojnë përdorimin e energjisë së rinovueshme',
  'Experience Smart Driving': 'Përjetoni Drejtimin e Zgjuar',
  
  // App.tsx additions
  //'Mobility': 'Mobiliteti',
  //'Next Electric Vehicle Alternative': 'Alternativa e Ardhshme e Automjeteve Elektrike',
  'Loading features...': 'Duke ngarkuar karakteristikat...',
  'Loading car details...': 'Duke ngarkuar detajet e makinës...',
  'Loading pricing form...': 'Duke ngarkuar formularin e çmimeve...',
  'Loading fleet...': 'Duke ngarkuar flotën...',
  'Loading about...': 'Duke ngarkuar rreth nesh...',
  'Loading contact...': 'Duke ngarkuar kontaktin...',
  'Loading technology...': 'Duke ngarkuar teknologjinë...',
  'Loading admin dashboard...': 'Duke ngarkuar panelin e administratorit...',
  '✓ Firebase Connected': '✓ Firebase i Lidhur',
  '⚠ Using Default Data': '⚠ Duke përdorur të dhëna parazgjedhje',
};

type Language = 'sq' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Safe localStorage check with try-catch for SSR compatibility
    try {
      const saved = typeof window !== 'undefined' ? localStorage.getItem('language') : null;
      return (saved === 'en' || saved === 'sq') ? saved as Language : 'sq'; // Default to Albanian
    } catch {
      return 'sq'; // Default to Albanian if localStorage fails
    }
  });

  useEffect(() => {
    // Save language preference to localStorage with error handling
    try {
      if (typeof window !== 'undefined') {
        localStorage.setItem('language', language);
      }
    } catch (error) {
      console.warn('Could not save language preference:', error);
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  // Ultra-simple translation function
  const t = (text: string): string => {
    // If English, return original text
    if (language === 'en') return text;
    // If Albanian, return translation or fallback to original
    return albanianTranslations[text] || text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};